### ISSUE TITLE
How do I use this code in game?

### ISSUE THREAD

**Issue by Hxzmxt** [med1844/TheBlockheadsTools#1]
I would like to know if I need to use a third party app or something to edit the code. Thank you.

**Comment by med1844** [comment]
You will have to extract the game save files from your device (iOS, android). You must get `data.mdb` `lock.mdb` to proceed. You may then use the library to modify `data.mdb` and write them back into your device.

This library is only targeted for developers, and can't magically change your in-game experience. Sorry for causing misunderstanding.
